### PR TITLE
Assignment

### PR DESCRIPTION
**Pull request by dnysius**
## What changes are you trying to make? (e.g. Adding or removing code, refactoring existing code, adding reports)
adding code to the project setup script

## What did you learn from the changes you have made?
mkdir, cp, rm, ls, redirect >, relative vs absolute paths, wildcards, recursive

## Was there another approach you were thinking about making? If so, what approach(es) were you thinking of?
I initially mkdir the parent directory separately, but found that you can specify -p parameter to do it all in one line. same result, but -p allows for cleaner code

## Were there any challenges? If so, what issue(s) did you face? How did you overcome it?
wasn't sure if moving rawdata to /data/raw meant moving the directory or the files within it. looking at the proceeding questions, i realized it can be either way if i adjust later on, but i chose to move the files within it to keep a flatter directory

## How were these changes tested?
checked that the expected directories were created, files are moved/copied as expected, ensured that ipaddr files were deleted, and the files that didnt meet the criteria were not copied to the new directory (i.e. misc data file)

## Checklist
- [x] I can confirm that my changes are working as intended

### CODE REVIEW

**Comment by dnysius** [comment]
autograder said in my previous PR attempt: 
rawdata not moved to data/raw

in this current PR attempt it cannot find log files in data/raw. is the expected result for the log files to be in data/raw, or the rawdata folder to be in data/raw? i.e. do we want data/raw/*.log or data/raw/rawdata/*.log? the test cases seem contradictory.

**Comment by monzchan** [comment]
@dnysius When you execute the command at question2, the content of the rawdata dir should be moved to data/raw. So, the log files should be in you data/raw dir instead of data/raw/rawdata.

**Comment by dnysius** [comment]
> @dnysius When you execute the command at question2, the content of the rawdata dir should be moved to data/raw. So, the log files should be in you data/raw dir instead of data/raw/rawdata.

Hi, this is what I did in the following closed PR, however the error thrown is that rawdata folder is not in data/raw. Aren't these 3 validation checks contradictory? https://github.com/dnysius/shell/pull/2

**Comment by monzchan** [comment]
image

In #2, the result of your command is what the question expect. 
But in question 2, you are moving the content of the rawdata dir, while the question requires you to move the rawdata dir. You may find the difference at the table I have posted

**Comment by dnysius** [comment]
> image
> 
> In #2, the result of your command is what the question expect. But in question 2, you are moving the content of the rawdata dir, while the question requires you to move the rawdata dir. You may find the difference at the table I have posted

I'm confused. Are you saying that in https://github.com/dnysius/shell/pull/2 I am doing what the question expects? If so, why is the autograder failing on "rawdata not moved to data/raw"?

To recap, here are the 2 situations I am facing:
1. I move the contents of rawdata into ./data/raw. This is what I am doing for this PR https://github.com/dnysius/shell/pull/2. I am getting the error saying that "rawdata not moved to data/raw"
2. I move the whole rawdata folder into ./data/raw, such that we now have ./data/raw/rawdata. This is what I'm doing for this current PR. I am getting the error stating that no log files are in ./data/raw.

What end result do we want? Because these test cases seem contradictory to me based on the wording.

**Comment by monzchan** [comment]
At #4 , you do:
  _**mkdir ./data/raw
  mv rawdata ./data/raw**_
Problem - No server log files in data/raw
These commands create the raw dir, and move rawdata dir into the raw dir, so the content of rawdata dir is not in data/raw

In #2, you do:
  _**mkdir ./data/raw
  mv rawdata/* ./data/raw**_
Problem - rawdata not moved to data/raw
These commands create the raw dir, and move only the content (files & subdirectories) of rawdata dir into the raw dir. But the original raw data directory will **still exist.**

Without creating a ./data/raw dir, you would be able to move the ./rawdata directory to ./data/raw
  _**mv ./rawdata ./data/raw**_
These commands move the entire rawdata dir (inc. all files, subdirectories, and metadata) into ./data and renames it to raw. After execution, the rawdata directory **no longer exists** in its original location.

**Comment by dnysius** [comment]
THANK YOU @monzchan 🥳 . This was infinitely clearer. I believe the question in the assignment nor the autograder test case result was not worded clearly.

1. question in the assignment should more specific, perhaps something along the lines of "# 2. Move the ./rawdata directory to ./data/raw such that the log files are in ./data/raw and ./rawdata no longer exists"

3. autograder test case should be updated from "rawdata not moved to data/raw" to something like "rawdata folder still exists"

**Pull request closed without merging**
